name: Deploy to GitHub Pages
on:
  push:
    # 你的主分支名，和当前仓库保持一致
    branches: [ main ] 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 安装依赖
        run: npm install

      - name: 构建Vite项目
        run: npm run build

      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 和你 vite.config.ts 里的 outDir 配置一致
          publish_dir: ./dist 